blank_issues_enabled: false
contact_links:
  - name: Feature Request | 特性请求
    url: https://github.com/linuxdeepin/unilang/discussions/new?category=features-request-ideas-%E7%89%B9%E6%80%A7%E8%AF%B7%E6%B1%82-%E5%A4%B4%E8%84%91%E9%A3%8E%E6%9A%B4
    about: Please create feature requests to the discussion board in our unilang repo.
  - name: General Discussion & Questions | 常规讨论与问答
    url: https://github.com/linuxdeepin/unilang/discussions/categories/q-a-%E9%97%AE%E7%AD%94%E6%9D%BF%E5%9D%97
    about: Please use the discussion board in our unilang repo.
